# https://dart.dev/tools/pub/pubspec

name: ekotel
description: OUA Bootcamp Project, F-37

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  flutter_riverpod: ^2.3.6
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/resimler/
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:        
    - family: RobotoBOLD
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf

    - family: RobotoBOLDItalic
      fonts:
        - asset: assets/fonts/RobotoCondensed-BoldItalic.ttf

    - family: RobotoItalic
      fonts:
        - asset: assets/fonts/RobotoCondensed-Italic.ttf

    - family: RobotoLight
      fonts:
        - asset: assets/fonts/RobotoCondensed-Light.ttf
    
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf


  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
